package io.github.joshmcrose.theme

import androidx.compose.foundation.text.selection.TextSelectionColors
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

@Immutable
data class ColorSchemes(
    val lightTheme: ThemeColors = DefaultLightThemeColors,
    val darkTheme: ThemeColors? = DefaultDarkThemeColors
)

internal val LocalColorScheme = staticCompositionLocalOf { DefaultLightThemeColors }

val DefaultLightThemeColors: ThemeColors = ThemeColors(
    appBackground = Color(0xFFEFEEE2),
    appBorder = Color(0xFFC7C8B8),
    macCloseIconColor = Color(red = 255, green = 59, blue = 48),
    macMinimizeIconColor = Color(red = 255, green = 204, blue = 0),
    macMaximizeIconColor = Color(red = 52, green = 199, blue = 89),
    macDisabledToolbarIconColor = Color.DarkGray,
    windowsToolbarIconColor = Color(0xFF3E4C0C),
    primary = Color(0xFF556523),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFD8EB9A),
    onPrimaryContainer = Color(0xFF3E4C0C),
    secondary = Color(0xFF5B6146),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFE0E6C4),
    onSecondaryContainer = Color(0xFF434930),
    tertiary = Color(0xFF3A665E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFBCECE2),
    onTertiaryContainer = Color(0xFF204E47),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    background = Color(0xFFFBFAED),
    onBackground = Color(0xFF1B1C15),
    surface = Color(0xFFFBFAED),
    onSurface = Color(0xFF1B1C15),
    surfaceVariant = Color(0xFFE3E4D3),
    onSurfaceVariant = Color(0xFF46483C),
    outline = Color(0xFF76786B),
    outlineVariant = Color(0xFFC7C8B8),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFF303129),
    inverseOnSurface = Color(0xFFF2F1E5),
    inversePrimary = Color(0xFFBCCF81),
    surfaceDim = Color(0xFFDBDBCF),
    surfaceBright = Color(0xFFFBFAED),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF5F4E8),
    surfaceContainer = Color(0xFFEFEEE2),
    surfaceContainerHigh = Color(0xFFE9E9DD),
    surfaceContainerHighest = Color(0xFFE4E3D7)
)

val DefaultDarkThemeColors: ThemeColors = ThemeColors(
    appBackground = Color(0xFF1F2019),
    appBorder = Color(0xFF46483C),
    macCloseIconColor = Color(red = 255, green = 69, blue = 58),
    macMinimizeIconColor = Color(red = 255, green = 212, blue = 38),
    macMaximizeIconColor = Color(red = 48, green = 240, blue = 88),
    macDisabledToolbarIconColor = Color.LightGray,
    windowsToolbarIconColor = Color(0xFFD8EB9A),
    primary = Color(0xFFBCCF81),
    onPrimary = Color(0xFF293500),
    primaryContainer = Color(0xFF3E4C0C),
    onPrimaryContainer = Color(0xFFD8EB9A),
    secondary = Color(0xFFC4CAA9),
    onSecondary = Color(0xFF2D331C),
    secondaryContainer = Color(0xFF434930),
    onSecondaryContainer = Color(0xFFE0E6C4),
    tertiary = Color(0xFFA1D0C6),
    onTertiary = Color(0xFF033730),
    tertiaryContainer = Color(0xFF204E47),
    onTertiaryContainer = Color(0xFFBCECE2),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF13140D),
    onBackground = Color(0xFFE4E3D7),
    surface = Color(0xFF13140D),
    onSurface = Color(0xFFE4E3D7),
    surfaceVariant = Color(0xFF46483C),
    onSurfaceVariant = Color(0xFFC7C8B8),
    outline = Color(0xFF909284),
    outlineVariant = Color(0xFF46483C),
    scrim = Color(0xFF000000),
    inverseSurface = Color(0xFFE4E3D7),
    inverseOnSurface = Color(0xFF303129),
    inversePrimary = Color(0xFF556523),
    surfaceDim = Color(0xFF13140D),
    surfaceBright = Color(0xFF393A32),
    surfaceContainerLowest = Color(0xFF0D0F08),
    surfaceContainerLow = Color(0xFF1B1C15),
    surfaceContainer = Color(0xFF1F2019),
    surfaceContainerHigh = Color(0xFF292B23),
    surfaceContainerHighest = Color(0xFF34352D)
)

data class ThemeColors(
    val appBackground: Color,
    val appBorder: Color = appBackground,
    val titlebarBackground: Color = appBackground,

    val macCloseIconColor: Color? = null,
    val macMinimizeIconColor: Color? = null,
    val macMaximizeIconColor: Color? = null,
    val macDisabledToolbarIconColor: Color? = null,

    val windowsToolbarIconColor: Color? = null,

    val textSelectionColors: TextSelectionColors? = null,

    val primary: Color? = null,
    val onPrimary: Color? = null,
    val primaryContainer: Color? = null,
    val onPrimaryContainer: Color? = null,
    val secondary: Color? = null,
    val onSecondary: Color? = null,
    val secondaryContainer: Color? = null,
    val onSecondaryContainer: Color? = null,
    val tertiary: Color? = null,
    val onTertiary: Color? = null,
    val tertiaryContainer: Color? = null,
    val onTertiaryContainer: Color? = null,
    val error: Color? = null,
    val onError: Color? = null,
    val errorContainer: Color? = null,
    val onErrorContainer: Color? = null,
    val background: Color? = null,
    val onBackground: Color? = null,
    val surface: Color? = null,
    val onSurface: Color? = null,
    val surfaceVariant: Color? = null,
    val onSurfaceVariant: Color? = null,
    val outline: Color? = null,
    val outlineVariant: Color? = null,
    val scrim: Color? = null,
    val inverseSurface: Color? = null,
    val inverseOnSurface: Color? = null,
    val inversePrimary: Color? = null,
    val surfaceDim: Color? = null,
    val surfaceBright: Color? = null,
    val surfaceContainerLowest: Color? = null,
    val surfaceContainerLow: Color? = null,
    val surfaceContainer: Color? = null,
    val surfaceContainerHigh: Color? = null,
    val surfaceContainerHighest: Color? = null,

    val themeColors: Map<String, Color>? = null
)